name: Auto Upload

on:
  push:
    branches:
      - "master"

permissions:
  id-token: write
  contents: read

jobs:
  Work:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout master
      uses: actions/checkout@v4
      with:
        ref: master

    - name: Login Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Clear Azure Storage
      uses: azure/CLI@v2
      with:
        inlineScript: |
          az storage blob delete-batch --account-name progczcomimagestorage --auth-mode login -s '$web'

    - name: Upload to Azure Storage
      uses: azure/CLI@v2
      with:
        inlineScript: |
          az storage blob upload-batch --account-name progczcomimagestorage --auth-mode login -d '$web' -s . --pattern "[!.]*" --overwrite true

    - name: Purge Azure CDN
      uses: azure/CLI@v2
      with:
        inlineScript: |
          az cdn endpoint purge -g blog-rg -n progczcom-image --profile-name progczcom-image-cdn --content-paths "/*" --no-wait true

    - name: Logout Azure
      run: |
        az logout
      if: always()
